services:
  dev-db:
    image: postgres:15
    container_name: movies-psql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - movies-pg-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: movies-redis
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'

volumes:
  movies-pg-data:
