services:
  dev-db:
    image: postgres:16
    container_name: movies-psql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - movies-pg-data:/var/lib/postgresql/data

volumes:
  movies-pg-data:
